Immediately load tasks of template
Fixes error:
ELException: Fehler beim Lesen von canBeUsedForProcess für den Typ
Template, caused by LazyInitializationException: failed to lazily
initialize collection tasks, could not initialize proxy - no Session

Rationale: number of task per template is small